added assertPackageLockVersion job to pr.yml AT-8616

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -12,6 +12,23 @@ permissions:
   contents: read
 
 jobs:
+  assertPackageLockVersion:
+    name: Ensure package-lock lockfileVersion has not changed
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout the repository
+        uses: actions/checkout@v3
+      - name: Check package-lock.json
+        run: |
+          file="package-lock.json"
+          expectedVersion="2"
+          lockFileVersion="$(jq -r .lockfileVersion "$file")"
+          if [ "$lockFileVersion" != "$expectedVersion" ]; then
+            echo "$file: lockfileVersion ($lockFileVersion) is invalid (expected: $expectedVersion)"
+            exit 1
+          else
+            echo "$file: lockfileVersion ($lockFileVersion) is the expected value ($expectedVersion)"
+          fi
   lint:
     name: Run linter
     runs-on: ubuntu-latest
